# Use the official MongoDB image as the base image
FROM mongo:latest

# Set environment variables (optional)
ENV MONGO_INITDB_ROOT_USERNAME=rootuser
ENV MONGO_INITDB_ROOT_PASSWORD=rootpass
 

# Expose the default MongoDB port
EXPOSE 27017
